### ISSUE TITLE
This is a test for Elvis' spreadsheet

### ISSUE THREAD

**Issue by Chekote** [Medology/phpunit-parallel-runner#16]
## Business Value:
[Want to read more on Types of Business Value?](https://docs.google.com/spreadsheets/d/1Bvcam238-mvESbTmEgLjkR0Dhrb9TmP4aQ7b3st8pMc/edit#gid=0)

<Type business value here! >

## Story:

**As a**  [ type of user ],
**I want** [ some goal ]
**so that** [ some reason ]

# Scenario-oriented Acceptance Criteria:

```gherkin
Scenario: the name for the behavior that will be described or Happy, Sad and Bad Path.
  Given the beginning state of the scenario 1
  
  When Event 1 for specific action that the user makes
  Then Outcome 1 for the action in “When”
  
  When Event 2 for specific action that the user makes
  Then Outcome 2 for the action in “When”
Scenario: the name for the behavior that will be described or Happy, Sad and Bad Path.
  Given the beginning state of the scenario 2
  
  When Event 1 for specific action that the user makes
  Then Outcome 1 for the action in “When”
  
  When Event 2 for specific action that the user makes
  Then Outcome 2 for the action in “When”
```

# Story Notes:

| Heading 1 | Heading 2 | Heading 3 |
|-----------|-----------|-----------|
| Content1  | Content2  | Content2  |

# Tasks:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Task Notes:

| Heading 1 | Heading 2 | Heading 3 |
|-----------|-----------|-----------|
| Content1  | Content2  | Content2  |

**Comment by hopeseekr** [comment]
@Chekote You really ought to check out Codeception. It is -so- much easier than Behat and accomplishes literally the same thing. I've automated the entire Amazon.com shopping flow using it.
