### ISSUE TITLE
Update to support php 7.1 and phpunit 7.5 at least.

### ISSUE THREAD

**Issue by manuerumx** [Medology/phpunit-parallel-runner#17]
The previous version supported (5.7) implements a custom printer option called `tap` This printer (and command line option `--tap`) was removed in the next version.

In order to upgrade other projects to newest versions of PHP and PHPUnit, is necessary to upgrade the support of this library.

**Comment by manuerumx** [comment]
Added support for PHP versions 7.1, 7.2 and 7.3

**Comment by MeganPartida** [comment]
### QA - Local
- No testing for this issue
- updating to **deploy & test**

**Comment by fortoulrodolfo** [comment]
## QA - Production
- Sanity Check performed and everything looks good. Its seems to be working fine.
- Updating ticket to **Approval**
