### ISSUE TITLE
Implement a custom description for Warnings on tests execution

### ISSUE THREAD

**Issue by manuerumx** [Medology/phpunit-parallel-runner#19]
Define and modify the warning level as displaying warnings on tests executions. 

The method `addWarning ` from the custom printer file `TapPrinter` can be customized in order to return more information about the test which throws a warning during their execution.

We are only incrementing a counter when we use addWarning at the moment. We should provide more information to help developers debug the issue.

**Comment by Chekote** [comment]
Closing this because this project is no longer maintained. We use CircleCI's test splitting by timing instead now.
