### ISSUE TITLE
Package not auto updated on Packagist

### ISSUE THREAD

**Issue by juanmrad** [Medology/phpunit-parallel-runner#31]
The package is not being auto updated on packagist

https://packagist.org/packages/medology/phpunit-parallel-runner

**Comment by izazueta** [comment]
* Will try to fix the issue today 
* Create PR or sent to approval if just a config change

**Comment by izazueta** [comment]
* Waiting for QA

**Comment by juliohl** [comment]
### QA Local
Nothing to tests since it is just a dependency change, moving to **D&T**.

**Comment by juliohl** [comment]
### QA Prod (#33)
Nothing to tests since it is just a dependency change, moving to **Approval**.

**Comment by izazueta** [comment]
* Waiting for SM approval

**Comment by izazueta** [comment]
Scored with @rashidsaf and @smijo149

**Comment by Chekote** [comment]
![Screen Shot 2020-05-13 at 3.31.05 PM.png](https://images.zenhubusercontent.com/57d18ae5e40e5714b16e8533/55f186ae-c8bc-4e51-b4e0-9940fbc6a406)
